In [1]:
import numpy as np
import pandas as pd
import CleanData as cd
import estandarizacion as st
import split_data as sd
from sklearn.decomposition import PCA

In [2]:
df = pd.read_csv('/home/relka/Escritorio/SS_VerPy/Dataset/NFL Play by Play 2009-2016 (v3).csv')

/tmp/ipykernel_336189/351934398.py:1: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/relka/Escritorio/SS_VerPy/Dataset/NFL Play by Play 2009-2016 (v3).csv')


In [3]:
cleaner = cd.CleanData()

In [13]:
dfc = cleaner.clean_nans(df=df,axis=1,method='fill',fill_value=np.mean(df.iloc[:,1]))

In [14]:
dfc.sample(5)

Date      GameID  Drive  qtr  down   time  TimeUnder  TimeSecs  \
338190  2016-10-30  2016103010     24    4   1.0  00:38          1      38.0   
147883  2012-10-07  2012100711     13    3   2.0  14:25         15    1765.0   
339283  2016-11-06  2016110602      2    1   1.0  10:27         11    3327.0   
336934  2016-10-30  2016103006      2    1   2.0  11:30         12    3390.0   
301340  2015-11-29  2015112907     22    4   1.0  08:54          9     534.0   

        PlayTimeDiff SideofField  ...        yacEPA  Home_WP_pre  Away_WP_pre  \
338190           8.0         DAL  ...  1.224741e-03     0.623299     0.376701   
147883          35.0          NO  ...  2.012664e+09     0.389498     0.610502   
339283          38.0         DAL  ...  2.012664e+09     0.514109     0.485891   
336934          38.0         SEA  ...  1.835957e+00     0.501640     0.498360   
301340           6.0         OAK  ...  2.012664e+09     0.501365     0.498635   

        Home_WP_post  Away_WP_post  Win_Prob       WPA        airWPA  \
338190      0.599200      0.400800  0.623299 -0.024098 -2.177308e-02   
147883      0.375509      0.624491  0.389498 -0.013989  2.012664e+09   
339283      0.544813      0.455187  0.485891 -0.030704  2.012664e+09   
336934      0.448470      0.551530  0.498360  0.053171 -2.442927e-03   
301340      0.477028      0.522972  0.501365 -0.024336  2.012664e+09   

              yacWPA  Season  
338190 -2.325196e-03    2016  
147883  2.012664e+09    2012  
339283  2.012664e+09    2016  
336934  5.561361e-02    2016  
301340  2.012664e+09    2015  

[5 rows x 102 columns]

In [7]:
dfc.head()

Date      GameID  Drive  qtr  TimeUnder  ydstogo  ydsnet  \
0  2009-09-10  2009091000      1    1         15        0       0   
1  2009-09-10  2009091000      1    1         15       10       5   
2  2009-09-10  2009091000      1    1         15        5       2   
3  2009-09-10  2009091000      1    1         14        8       2   
4  2009-09-10  2009091000      1    1         14        8       2   

   PlayAttempted  Yards.Gained  sp  ...  AwayTeam  Timeout_Indicator  \
0              1            39   0  ...       TEN                  0   
1              1             5   0  ...       TEN                  0   
2              1            -3   0  ...       TEN                  0   
3              1             0   0  ...       TEN                  0   
4              1             0   0  ...       TEN                  0   

   posteam_timeouts_pre HomeTimeouts_Remaining_Pre  \
0                     3                          3   
1                     3                          3   
2                     3                          3   
3                     3                          3   
4                     3                          3   

   AwayTimeouts_Remaining_Pre  HomeTimeouts_Remaining_Post  \
0                           3                            3   
1                           3                            3   
2                           3                            3   
3                           3                            3   
4                           3                            3   

   AwayTimeouts_Remaining_Post  ExPoint_Prob  TwoPoint_Prob  Season  
0                            3           0.0            0.0    2009  
1                            3           0.0            0.0    2009  
2                            3           0.0            0.0    2009  
3                            3           0.0            0.0    2009  
4                            3           0.0            0.0    2009  

[5 rows x 37 columns]

In [8]:
df.shape

(362447, 102)

In [9]:
dfc.shape

(362447, 37)

In [10]:
dfc2 = df.dropna(axis=1)

In [11]:
dfc2.shape 

(362447, 37)

In [4]:
X = df.iloc[:,2:4]

In [13]:
Xprom = np.mean(X)
Xprom

np.float64(7.462659368128306)

In [14]:
import numpy as np

# Crear una matriz (lista de listas)
matriz = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

# Convertir la matriz a un array de NumPy
array_matriz = np.array(matriz)

# Calcular el promedio de todos los elementos
promedio_total = np.mean(array_matriz)
print(f"Promedio total: {promedio_total}")

# Calcular el promedio por filas (axis=1)
promedio_filas = np.mean(array_matriz, axis=1)
print(f"Promedio por filas: {promedio_filas}")

# Calcular el promedio por columnas (axis=0)
promedio_columnas = np.mean(array_matriz, axis=0)
print(f"Promedio por columnas: {promedio_columnas}")

Promedio total: 5.0
Promedio por filas: [2. 5. 8.]
Promedio por columnas: [4. 5. 6.]


In [33]:
Xvalues = X.values

In [16]:
Xvalues

array([[ 1,  1],
       [ 1,  1],
       [ 1,  1],
       ...,
       [21,  4],
       [21,  4],
       [21,  4]], shape=(362447, 2))

In [17]:
Xprom = np.mean(Xvalues , axis=0)

In [18]:
Xprom

array([12.34708799,  2.57823075])

In [19]:
Xstd = np.std(Xvalues, axis=0)
Xstd

array([7.16816299, 1.13025754])

In [20]:
Xs = (X-Xprom)/Xstd

In [12]:
df.iloc[:,0:10].isnull().sum()

Date                0
GameID              0
Drive               0
qtr                 0
down            54218
time              188
TimeUnder           0
TimeSecs          188
PlayTimeDiff      374
SideofField       450
dtype: int64

In [5]:
y=df['TimeSecs'].values


In [6]:
type(y)

numpy.ndarray

In [14]:
y.isnull().sum()

np.int64(188)

In [6]:
X.isnull().sum()

Drive    0
qtr      0
dtype: int64

In [15]:
y.head()

0    3600.0
1    3593.0
2    3556.0
3    3515.0
4    3507.0
Name: TimeSecs, dtype: float64

In [23]:
a='hola mundo'

In [6]:

std = st.Standardization(X,y)

In [25]:
a='hola mundo'

In [26]:
Xs,ys =std.standardize(X,y)

In [27]:
Xs

Drive       qtr
0      -1.582984 -1.396346
1      -1.582984 -1.396346
2      -1.582984 -1.396346
3      -1.582984 -1.396346
4      -1.582984 -1.396346
...          ...       ...
362442  1.067625  1.257916
362443  1.067625  1.257916
362444  1.207131  1.257916
362445  1.207131  1.257916
362446  1.207131  1.257916

[362447 rows x 2 columns]

In [28]:
ys

0         1.640181
1         1.640181
2         1.640181
3         1.424762
4         1.424762
            ...   
362442   -1.375679
362443   -1.375679
362444   -1.375679
362445   -1.375679
362446   -1.591098
Name: TimeUnder, Length: 362447, dtype: float64

In [29]:
split = sd.SplitData(X, y, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test = split.split_data()

In [30]:
X_train

Drive  qtr
128550     10    3
133422     10    2
343058      1    1
56448      11    2
224000     15    3
...       ...  ...
317376     22    4
110712     13    3
57468       3    1
208503     24    4
353763      3    1

[72489 rows x 2 columns]

In [31]:
X.shape

(362447, 2)

In [34]:
type(X.values)

numpy.ndarray

In [35]:
if isinstance(X.values, np.ndarray):
    print('X is a numpy array')

X is a numpy array


In [36]:
df


Date      GameID  Drive  qtr  down   time  TimeUnder  TimeSecs  \
0       2009-09-10  2009091000      1    1   NaN  15:00         15    3600.0   
1       2009-09-10  2009091000      1    1   1.0  14:53         15    3593.0   
2       2009-09-10  2009091000      1    1   2.0  14:16         15    3556.0   
3       2009-09-10  2009091000      1    1   3.0  13:35         14    3515.0   
4       2009-09-10  2009091000      1    1   4.0  13:27         14    3507.0   
...            ...         ...    ...  ...   ...    ...        ...       ...   
362442  2017-01-01  2017010102     20    4   1.0  00:22          1      22.0   
362443  2017-01-01  2017010102     20    4   NaN  00:13          1      13.0   
362444  2017-01-01  2017010102     21    4   NaN  00:13          1      13.0   
362445  2017-01-01  2017010102     21    4   1.0  00:12          1      12.0   
362446  2017-01-01  2017010102     21    4   NaN  00:00          0       0.0   

        PlayTimeDiff SideofField  ...    yacEPA  Home_WP_pre  Away_WP_pre  \
0                0.0         TEN  ...       NaN     0.485675     0.514325   
1                7.0         PIT  ...  1.146076     0.546433     0.453567   
2               37.0         PIT  ...       NaN     0.551088     0.448912   
3               41.0         PIT  ... -5.031425     0.510793     0.489207   
4                8.0         PIT  ...       NaN     0.461217     0.538783   
...              ...         ...  ...       ...          ...          ...   
362442           6.0          GB  ...  0.000000     0.051901     0.948099   
362443           9.0          GB  ...       NaN     0.093435     0.906565   
362444           0.0         DET  ...       NaN     0.034069     0.965931   
362445           1.0         DET  ...       NaN     0.035708     0.964292   
362446          12.0         DET  ...       NaN     0.000000     1.000000   

        Home_WP_post  Away_WP_post  Win_Prob       WPA    airWPA    yacWPA  \
0           0.546433      0.453567  0.485675  0.060758       NaN       NaN   
1           0.551088      0.448912  0.546433  0.004655 -0.032244  0.036899   
2           0.510793      0.489207  0.551088 -0.040295       NaN       NaN   
3           0.461217      0.538783  0.510793 -0.049576  0.106663 -0.156239   
4           0.558929      0.441071  0.461217  0.097712       NaN       NaN   
...              ...           ...       ...       ...       ...       ...   
362442      0.093435      0.906565  0.051901  0.041534  0.041534  0.000000   
362443      0.034069      0.965931  0.093435 -0.059366       NaN       NaN   
362444      0.035708      0.964292  0.965931 -0.001639       NaN       NaN   
362445      0.000000      1.000000  0.964292  0.035708       NaN       NaN   
362446      0.000000      1.000000  0.934245  0.000000       NaN       NaN   

        Season  
0         2009  
1         2009  
2         2009  
3         2009  
4         2009  
...        ...  
362442    2016  
362443    2016  
362444    2016  
362445    2016  
362446    2016  

[362447 rows x 102 columns]

In [43]:
df.dropna(axis=1)

Date      GameID  Drive  qtr  TimeUnder  ydstogo  ydsnet  \
0       2009-09-10  2009091000      1    1         15        0       0   
1       2009-09-10  2009091000      1    1         15       10       5   
2       2009-09-10  2009091000      1    1         15        5       2   
3       2009-09-10  2009091000      1    1         14        8       2   
4       2009-09-10  2009091000      1    1         14        8       2   
...            ...         ...    ...  ...        ...      ...     ...   
362442  2017-01-01  2017010102     20    4          1       10      35   
362443  2017-01-01  2017010102     20    4          1        0      35   
362444  2017-01-01  2017010102     21    4          1        0       0   
362445  2017-01-01  2017010102     21    4          1       10      -1   
362446  2017-01-01  2017010102     21    4          0        0      -1   

        PlayAttempted  Yards.Gained  sp  ...  AwayTeam  Timeout_Indicator  \
0                   1            39   0  ...       TEN                  0   
1                   1             5   0  ...       TEN                  0   
2                   1            -3   0  ...       TEN                  0   
3                   1             0   0  ...       TEN                  0   
4                   1             0   0  ...       TEN                  0   
...               ...           ...  ..  ...       ...                ...   
362442              1            35   1  ...        GB                  0   
362443              1             0   1  ...        GB                  0   
362444              1             0   0  ...        GB                  0   
362445              1            -1   0  ...        GB                  0   
362446              1             0   0  ...        GB                  0   

        posteam_timeouts_pre HomeTimeouts_Remaining_Pre  \
0                          3                          3   
1                          3                          3   
2                          3                          3   
3                          3                          3   
4                          3                          3   
...                      ...                        ...   
362442                     0                          0   
362443                     0                          0   
362444                     0                          0   
362445                     0                          0   
362446                     0                          0   

        AwayTimeouts_Remaining_Pre  HomeTimeouts_Remaining_Post  \
0                                3                            3   
1                                3                            3   
2                                3                            3   
3                                3                            3   
4                                3                            3   
...                            ...                          ...   
362442                           0                            0   
362443                           0                            0   
362444                           0                            0   
362445                           0                            0   
362446                           0                            0   

        AwayTimeouts_Remaining_Post  ExPoint_Prob  TwoPoint_Prob  Season  
0                                 3      0.000000            0.0    2009  
1                                 3      0.000000            0.0    2009  
2                                 3      0.000000            0.0    2009  
3                                 3      0.000000            0.0    2009  
4                                 3      0.000000            0.0    2009  
...                             ...           ...            ...     ...  
362442                            0      0.000000            0.0    2016  
362443                            0      0.931115            0.0    2016  
362444     

El data frame contiene valores nulos


In [7]:
cleaner = cd.CleanData()

In [9]:
type(X)

pandas.core.frame.DataFrame

In [8]:
Xcn = cleaner.clean_nans(X,axis=0,method='drop')

In [7]:
type(Xcn)

pandas.core.frame.DataFrame

In [9]:
ycn = cleaner.clean_nans(y,axis=0,method='drop')

In [10]:
st = st.Standardization(Xcn,ycn)

In [12]:
Xs,ys, yprom, ystd,Xprom,Xstd= st.standardize(Xcn,ycn)

In [9]:
X.shape[0] == Xcn.shape[0]

True

In [10]:
Xcn.shape[0] == y.shape[0]

True

In [52]:
a=df.dropna(axis=1).isnull().sum() == 0

In [55]:
len(a)

37

In [57]:
for i in range(len(a)):
    if a[i]:
        print(f'No missing values in {i+1}')
    

No missing values in 1
No missing values in 2
No missing values in 3
No missing values in 4
No missing values in 5
No missing values in 6
No missing values in 7
No missing values in 8
No missing values in 9
No missing values in 10
No missing values in 11
No missing values in 12
No missing values in 13
No missing values in 14
No missing values in 15
No missing values in 16
No missing values in 17
No missing values in 18
No missing values in 19
No missing values in 20
No missing values in 21
No missing values in 22
No missing values in 23
No missing values in 24
No missing values in 25
No missing values in 26
No missing values in 27
No missing values in 28
No missing values in 29
No missing values in 30
No missing values in 31
No missing values in 32
No missing values in 33
No missing values in 34
No missing values in 35
No missing values in 36
No missing values in 37


/tmp/ipykernel_85608/3131297216.py:2: FutureWarning: Series.__getitem__ treating keys as positions is deprecated. In a future version, integer keys will always be treated as labels (consistent with DataFrame behavior). To access a value by position, use `ser.iloc[pos]`
  if a[i]:


In [32]:
pca=PCA(n_components=2)

In [33]:
pca.fit(X)

PCA(n_components=2)

In [34]:
coeff = pca.components_


In [35]:
score = pca.transform(X)

In [26]:
latent = pca.explained_variance_

In [27]:
print(pca.explained_variance_ratio_)

[0.99621316]


In [28]:
X_transformed = pca.transform(X)

In [36]:
m = score.shape[0]

In [40]:
X_transformed_pca = np.concatenate((np.ones((m,1)), score), axis=1)


In [41]:
a = np.zeros((10,10))

In [42]:
type(y)

numpy.ndarray

In [43]:
X*y

ValueError: Unable to coerce to Series, length must be 2: given 362447

In [45]:
np.dot(X.T,y)

array([nan, nan])

In [46]:
X.T @ y

Drive   NaN
qtr     NaN
dtype: float64