In [1]:
import numpy as np
import pandas as pd
import CleanData as cd
import estandarizacion as st
import split_data as sd

In [2]:
df = pd.read_csv('/home/relka/Escritorio/SS_VerPy/Dataset/NFL Play by Play 2009-2016 (v3).csv')

/tmp/ipykernel_458385/351934398.py:1: DtypeWarning: Columns (25,51) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv('/home/relka/Escritorio/SS_VerPy/Dataset/NFL Play by Play 2009-2016 (v3).csv')


In [3]:
cleaner = cd.CleanData(df)

In [4]:
dfc = cleaner.clean_nans(axis=1,method='drop')

In [5]:
dfc.head()

Date      GameID  Drive  qtr  TimeUnder  ydstogo  ydsnet  \
0  2009-09-10  2009091000      1    1         15        0       0   
1  2009-09-10  2009091000      1    1         15       10       5   
2  2009-09-10  2009091000      1    1         15        5       2   
3  2009-09-10  2009091000      1    1         14        8       2   
4  2009-09-10  2009091000      1    1         14        8       2   

   PlayAttempted  Yards.Gained  sp  ...  AwayTeam  Timeout_Indicator  \
0              1            39   0  ...       TEN                  0   
1              1             5   0  ...       TEN                  0   
2              1            -3   0  ...       TEN                  0   
3              1             0   0  ...       TEN                  0   
4              1             0   0  ...       TEN                  0   

   posteam_timeouts_pre HomeTimeouts_Remaining_Pre  \
0                     3                          3   
1                     3                          3   
2                     3                          3   
3                     3                          3   
4                     3                          3   

   AwayTimeouts_Remaining_Pre  HomeTimeouts_Remaining_Post  \
0                           3                            3   
1                           3                            3   
2                           3                            3   
3                           3                            3   
4                           3                            3   

   AwayTimeouts_Remaining_Post  ExPoint_Prob  TwoPoint_Prob  Season  
0                            3           0.0            0.0    2009  
1                            3           0.0            0.0    2009  
2                            3           0.0            0.0    2009  
3                            3           0.0            0.0    2009  
4                            3           0.0            0.0    2009  

[5 rows x 37 columns]

In [6]:
df.shape

(362447, 102)

In [7]:
dfc.shape

(362447, 37)

In [8]:
dfc2 = df.dropna(axis=1)

In [9]:
dfc2.shape 

(362447, 37)

In [10]:
X = df.iloc[:,2:4]

In [11]:
Xprom = np.mean(X)
Xprom

np.float64(7.462659368128306)

In [12]:
import numpy as np

# Crear una matriz (lista de listas)
matriz = [[1, 2, 3],
          [4, 5, 6],
          [7, 8, 9]]

# Convertir la matriz a un array de NumPy
array_matriz = np.array(matriz)

# Calcular el promedio de todos los elementos
promedio_total = np.mean(array_matriz)
print(f"Promedio total: {promedio_total}")

# Calcular el promedio por filas (axis=1)
promedio_filas = np.mean(array_matriz, axis=1)
print(f"Promedio por filas: {promedio_filas}")

# Calcular el promedio por columnas (axis=0)
promedio_columnas = np.mean(array_matriz, axis=0)
print(f"Promedio por columnas: {promedio_columnas}")

Promedio total: 5.0
Promedio por filas: [2. 5. 8.]
Promedio por columnas: [4. 5. 6.]


In [13]:
Xvalues = X.values

In [14]:
Xvalues

array([[ 1,  1],
       [ 1,  1],
       [ 1,  1],
       ...,
       [21,  4],
       [21,  4],
       [21,  4]], shape=(362447, 2))

In [15]:
Xprom = np.mean(Xvalues , axis=0)

In [16]:
Xprom

array([12.34708799,  2.57823075])

In [17]:
Xstd = np.std(Xvalues, axis=0)
Xstd

array([7.16816299, 1.13025754])

In [18]:
Xs = (X-Xprom)/Xstd

In [19]:
y=df.iloc[:,6]

In [20]:
y.head()

0    15
1    15
2    15
3    14
4    14
Name: TimeUnder, dtype: int64

In [21]:
a='hola mundo'

In [22]:

std = st.Standardization(X,y)

In [23]:
a='hola mundo'

In [24]:
Xs,ys =std.standardize(X,y)

In [25]:
Xs

Drive       qtr
0      -1.582984 -1.396346
1      -1.582984 -1.396346
2      -1.582984 -1.396346
3      -1.582984 -1.396346
4      -1.582984 -1.396346
...          ...       ...
362442  1.067625  1.257916
362443  1.067625  1.257916
362444  1.207131  1.257916
362445  1.207131  1.257916
362446  1.207131  1.257916

[362447 rows x 2 columns]

In [26]:
ys

0         1.640181
1         1.640181
2         1.640181
3         1.424762
4         1.424762
            ...   
362442   -1.375679
362443   -1.375679
362444   -1.375679
362445   -1.375679
362446   -1.591098
Name: TimeUnder, Length: 362447, dtype: float64

In [28]:
split = sd.SplitData(X, y, test_size=0.2, random_state=42)
X_train, X_test, y_train, y_test = split.split_data()

In [29]:
X_train

Drive  qtr
128550     10    3
133422     10    2
343058      1    1
56448      11    2
224000     15    3
...       ...  ...
317376     22    4
110712     13    3
57468       3    1
208503     24    4
353763      3    1

[72489 rows x 2 columns]

In [30]:
X.shape

(362447, 2)